### PR TITLE
Add the possibility to compile Dwarf Therapist with Qt5

### PR DESCRIPTION
**Pull request by ytterbium**
I added the possibility to compile the latest version of Dwarf Therapist with Qt5, for those who can. It can be useful for people who can do it and who want to use the latest version of DT.  It is always possible to stick to the Qt4 version. 

I had to change the step of compiling DT, because I didn't succeed to compile with Qt5 through the previous way; but is probably because I do not master the subtleties of qmake and make.

I hope it is quality enough to be incorporated.

### CODE REVIEW

**Comment by andrewd18** [comment]
Why do you ask the user if they want the QT5 version? Either the newer version of DF Therapist is better, or it is not. The user shouldn't have to choose, they should always get the best.

Furthermore, the QT4 version is unmaintained and will not be updated by the maintainer when DF2014 comes out. I would rather see this issue get fixed by enforcing a mandatory QT5 upgrade.

Edit: Your code quality is fine; no worries there. :)

**Comment by ytterbium** [comment]
I ask about the Qt5 in case the user doesn't have all the needed Qt5 environment, only qmake-qt5.
I could replace this by checking in check_dependencies if there all the libraries needed by Dwarf Therapist

**Comment by ytterbium** [comment]
It's normally done.

**Comment by OliverUv** [comment]
cat /etc/os-release> NAME="Ubuntu", VERSION="13.10, Saucy Salamander" (really Linux Mint 16 Petra)

I installed qtcreator from repos some time ago, it installed qt5-qmake and other packages. Though I didn't get any qt5-qmake/qmake-qt5 binary (did get docs though). Even though the binary didn't exist, the script tried to use qt5. I just apt-get removed the qt5-qmake package, and the lnp install went fine with qt4. Just wanted you to know there's a possibility that you detect qt5 packages while systems might not actually have the binary.

**Comment by Argon0** [comment]
<ack> Been trying to get this to work on my Ubuntu installation for the last couple of hours - just get failure after failure. Running 13.10.

I've installed the qt5-make package, and all the other dependencies. I get so far then... I know qt5 is there as qtchooser tells me. I've set qt5 as the default but...

First off I get the checksum error with  Utility_Plugins_v0.44-Windows-0.34.11.r3.zip.zip so I used the --skip-sha option.

Then I get cannot compile and see this message:

./df-lnp-installer.sh: 64: ./df-lnp-installer.sh: qmake-qt5: not found

df-lnp-installer.sh: Compiling Dwarf Therapist failed. See QMake output above for details. Exiting.

I know qmake is there (which qmake gives /usr/bin/qmake - which links to qtchooser...)

What am I missing?

Argon0

**Comment by Argon0** [comment]
So then I went back and tried what OliverUv suggested (removing qt5-qmake) and installed qt4-qmake, and I got this:

qmake: could not find a Qt installation of ''
Project MESSAGE: Release Mode
Project MESSAGE: Setting up for Linux
Project MESSAGE: Setting up for Linux Install
/usr/lib/i386-linux-gnu/qt4/bin/uic ui/scriptdialog.ui -o bin/release/ui_scriptdialog.h
make: /usr/lib/i386-linux-gnu/qt4/bin/uic: Command not found
make: **\* [bin/release/ui_scriptdialog.h] Error 127

df-lnp-installer.sh: Compiling Dwarf Therapist failed. See Make output above for details. Exiting.

HAYELP!! (I just want to install DF!!)

**Comment by OliverUv** [comment]
Installing libqt4-dev might help. Good luck!

**Pull request merged**
